version: "3"
services:
  resources:
    build: 
      context: resources
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"

volumes:
  postgres-data: null
