version: "3"
services:

  # ----- API STACK -----
  api:
    build: 
      context: api
      dockerfile: Dockerfile
    ports: 
      - "9090:80"
    depends_on:
      - mongo
    networks:
      - mongo 
      - default

  mongo:
    image: mongo:4  # The CPU of my MacBook does not support newer version
    restart: always
    volumes: 
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:mongodb@mongo:27017/
    networks:
      - mongo 
      - default

  # ----- SCRAPER ----- 
  scraper: 
    build: 
      context: scraper 
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
    networks: 
      - default 
    environment:
      - APP_CONFIG_API_URL=http://api
      - APP_CONFIG_WAIT_DURATION=24h

volumes:
  mongo-data: null

networks:
  mongo:
