version: "3"
services:

  # RESOURCES STACK
  resources:
    build: 
      context: resources
      dockerfile: Dockerfile
    environment:
      RUN_MIGRATION: 1
    ports: 
      - "8080:8080"
    depends_on:
      - resources_db

  resources_db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"


  # SNAPSHOTS STACK
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:mongodb@mongo:27017/

volumes:
  postgres-data: null
