version: "3"
services:

  # ----- RESOURCES STACK -----
  resources:
    build: 
      context: resources
      dockerfile: Dockerfile
    environment:
      RUN_MIGRATION: 1
      APP_CONFIG_DB_USER: postgres
      APP_CONFIG_DB_PASSWORD: postgres
      APP_CONFIG_DB_HOST: postgres:5432
    ports: 
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - default
      - resources

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - resources

  # ----- SNAPSHOTS STACK -----
  snapshots:
    build: 
      context: snapshots
      dockerfile: Dockerfile
    ports: 
      - "9090:80"
    depends_on:
      - mongo
    networks:
      - snapshots 
      - default

  mongo:
    image: mongo:4  # The CPU of my MacBook does not support newer version
    restart: always
    volumes: 
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    networks:
      - snapshots

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:mongodb@mongo:27017/
    networks:
      - snapshots 
      - default

  # ----- SCRAPER ----- 
  scraper: 
    build: 
      context: scraper 
      dockerfile: Dockerfile
    depends_on:
      - snapshots
      - resources
    networks: 
      - default 
    environment:
      - APP_CONFIG_RESOURCE_API=http://resources
      - APP_CONFIG_SNAPSHOT_API=http://snapshots
      - APP_CONFIG_WAIT_DURATION=24h

volumes:
  postgres-data: null
  mongo-data: null

networks:
  resources:
  snapshots:
