version: '3.8'

services:
  resources-dev:
    build:
      context: resources
      dockerfile: .devcontainer/Dockerfile

    # Set environment variables
    environment: 
      RUN_MIGRATION: 0
      APP_CONFIG_DB_USER: postgres
      APP_CONFIG_DB_PASSWORD: postgres
      APP_CONFIG_DB_HOST: postgres:5432

    # Mount source
    volumes:
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - default
      - resources
