version: '3.8'

services:
  resources:
    build:
      context: resources
      dockerfile: .devcontainer/Dockerfile

    # Set environment variables
    environment: 
      RUN_MIGRATION: 0

    # Mount source
    volumes:
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
